---
name: "Enhancement"
description: "Suggest an idea for this project"
labels: 
- "enhancement"

body:

- type: markdown
  attributes:
    value: Before you open a new enhancement request, search through the existing enhancement requests to see if others have had the same idea.

- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have filled out the template to the best of my ability.
        required: true
      - label: This only contains 1 enhancement request (if you have multiple requests, open a new request for each enhancement).
        required: true
      - label: This issue is not a duplicate enhancement request ([search previous requests](https://github.com/thlucas1/homeassistantcomponent_spotifyplus/issues?q=is%3Aissue+label%3Aenhancement).
        required: true

- type: textarea
  attributes:
    label: "Is your enhancement request related to a problem? Please describe."
    description: "A clear and concise description of what the problem is."
    placeholder: "I'm always frustrated when [...]"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Describe the solution you'd like"
    description: "A clear and concise description of what you want to happen."
  validations:
    required: true

- type: textarea
  attributes:
    label: "Describe alternatives you've considered"
    description: "A clear and concise description of any alternative solutions or enhancements you've considered."
  validations:
    required: true

- type: textarea
  attributes:
    label: "Additional context"
    description: "Add any other context or screenshots about the enhancement request here."
  validations:
    required: true
